#Figure 4 : Figure de votre choix CUBE
import turtle
t = turtle.Turtle()
from turtle import*
cote=4
for i in range(cote):
         forward(50)
         left(360/cote)
t.up()
t.goto(25,0)
t.down()
t.right(90)
t.forward(25)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.up()
t.goto(0,0)
t.down()
t.right(45)
t.forward(35)
t.up()
t.goto(0,50)
t.down()
t.forward(35)
t.up()
t.goto(50,50)
t.down()
t.forward(35)
t.up()
t.goto(50,0)
t.down()
t.forward(35)